"""
PTB-XL downloader and ECG image generator.

This module:
- downloads PTB-XL metadata
- builds a numeric CSV dataset from metadata
- downloads WFDB signal pairs (.hea and .dat)
- renders ECG traces into PNG images
"""

from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import pandas as pd
import requests
import wfdb

from cardioia.state import ManifestDB
from cardioia.utils import ensure_dir


def _download_text(url: str) -> str:
    response = requests.get(url, timeout=60)
    response.raise_for_status()
    return response.text


def _save_metadata(url: str, destination: Path) -> Path:
    response = requests.get(url, timeout=60)
    response.raise_for_status()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(response.content)
    return destination


def _build_record_urls(base_url: str, relative_path: str) -> tuple[str, str]:
    """
    Build PTB-XL WFDB URLs for .hea and .dat.
    """
    return (
        f"{base_url}/{relative_path}.hea",
        f"{base_url}/{relative_path}.dat",
    )


def _download_binary_to_bytes(url: str) -> bytes:
    response = requests.get(url, timeout=60)
    response.raise_for_status()
    return response.content


def _write_record_from_bytes(record_base_path: Path, hea_bytes: bytes, dat_bytes: bytes) -> None:
    record_base_path.parent.mkdir(parents=True, exist_ok=True)
    record_base_path.with_suffix(".hea").write_bytes(hea_bytes)
    record_base_path.with_suffix(".dat").write_bytes(dat_bytes)


def _render_ecg_to_png(record_base_path: Path, output_png: Path) -> None:
    """
    Read a local WFDB record and render a simple ECG chart to PNG.
    """
    record = wfdb.rdrecord(str(record_base_path))
    signal = record.p_signal

    output_png.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(16, 9))
    for lead_index in range(min(signal.shape[1], 12)):
        plt.plot(signal[:, lead_index], linewidth=0.6)

    plt.title(f"ECG Record: {record_base_path.name}")
    plt.xlabel("Samples")
    plt.ylabel("Amplitude")
    plt.tight_layout()
    plt.savefig(output_png, dpi=150)
    plt.close()


def run_ptbxl(config: dict[str, Any], count: int) -> None:
    """
    Execute PTB-XL pipeline.

    Parameters
    ----------
    config : dict[str, Any]
        Loaded YAML configuration.
    count : int
        Number of ECG records/images to process.
    """
    paths = config["paths"]
    ptbxl = config["ptbxl"]

    output_numeric_dir = ensure_dir(paths["numeric_dir"])
    output_image_dir = ensure_dir(paths["image_dir"])
    download_dir = ensure_dir(paths["download_dir"])
    manifest = ManifestDB(paths["state_db"])

    base_url = ptbxl["base_url"]
    resolution = ptbxl.get("waveform_resolution", "lr")
    metadata_cfg = ptbxl["metadata"]

    ptbxl_csv_url = metadata_cfg["ptbxl_database_csv"][0]
    scp_csv_url = metadata_cfg["scp_statements_csv"][0]

    ptbxl_csv_path = output_numeric_dir / "ptbxl_database.csv"
    scp_csv_path = output_numeric_dir / "scp_statements.csv"

    if not manifest.exists("ptbxl_metadata", "ptbxl_database.csv"):
        _save_metadata(ptbxl_csv_url, ptbxl_csv_path)
        manifest.add("ptbxl_metadata", "ptbxl_database.csv", ptbxl_csv_url, str(ptbxl_csv_path))

    if not manifest.exists("ptbxl_metadata", "scp_statements.csv"):
        _save_metadata(scp_csv_url, scp_csv_path)
        manifest.add("ptbxl_metadata", "scp_statements.csv", scp_csv_url, str(scp_csv_path))

    df = pd.read_csv(ptbxl_csv_path)

    selected_columns = [
        col for col in [
            "ecg_id",
            "patient_id",
            "age",
            "sex",
            "height",
            "weight",
            "nurse",
            "site",
            "device",
            "recording_date",
            "report",
            "heart_axis",
            "infarction_stadium1",
            "infarction_stadium2",
            "validated_by",
            "second_opinion",
            "initial_autogenerated_report",
            "filename_lr",
            "filename_hr",
            "scp_codes",
        ]
        if col in df.columns
    ]

    numeric_dataset_path = output_numeric_dir / "ptbxl_numeric_dataset.csv"
    df[selected_columns].to_csv(numeric_dataset_path, index=False)

    processed = 0
    for _, row in df.iterrows():
        if processed >= count:
            break

        ecg_id = str(row["ecg_id"])
        resource_id = f"ecg_{ecg_id}"

        if manifest.exists("ptbxl_image", resource_id):
            continue

        relative_path = row["filename_lr"] if resolution == "lr" else row["filename_hr"]
        hea_url, dat_url = _build_record_urls(base_url, relative_path)

        local_record_base = download_dir / relative_path

        try:
            hea_bytes = _download_binary_to_bytes(hea_url)
            dat_bytes = _download_binary_to_bytes(dat_url)

            _write_record_from_bytes(local_record_base, hea_bytes, dat_bytes)

            output_png = output_image_dir / f"{resource_id}.png"
            _render_ecg_to_png(local_record_base, output_png)

            manifest.add("ptbxl_image", resource_id, hea_url, str(output_png))
            processed += 1
            print(f"[OK] ECG processed: {resource_id}")

        except Exception as exc:
            print(f"[WARN] Failed to process {resource_id}: {exc}")

    manifest.close()
    print(f"[DONE] PTB-XL pipeline finished. Images generated: {processed}")
