project:
  name: cardioia-fase1

ptbxl:
  base_url: "https://physionet.org/files/ptb-xl/1.0.3"
  metadata:
    ptbxl_database_csv:
      - "https://physionet.org/files/ptb-xl/1.0.3/ptbxl_database.csv"
    scp_statements_csv:
      - "https://physionet.org/files/ptb-xl/1.0.3/scp_statements.csv"

  waveform_resolution: "lr"   # lr -> records100 | hr -> records500

paths:
  output_root: "data"
  numeric_dir: "data/numeric"
  image_dir: "data/images/ptbxl"
  download_dir: "data/downloads/ptbxl"
  state_db: "data/state/manifest.db"
